app = 'ride42api'
primary_region = 'yyz'

# DO NOT STORE SENSITIVE ENV HERE! Use fly secrets instead.
[env]
  MAIL_LISTENER_MACHINE="1857501f1034d8"
  STRIPE_FEE=5
  DAYS_LOCKOUT=7
  LATE_ALLOWANCE_HOURS=12
  GROUP_CAPACITY=30

[http_service]
  internal_port = 443
  force_https = true
  processes = ['app']
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
