# fly.toml app configuration file generated for ride42api on 2024-03-31T21:10:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ride42api'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 443
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
